spring:
  application:
    name: spring-test-project
  datasource:
    url: jdbc:h2:mem:testdb
    username: testuser
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /test
  port: 8081
logging:
  level:
    org:
      springframework:
        web: TRACE